### ISSUE TITLE
Synthetic Script timeout

### ISSUE THREAD

**Issue by Lucy0** [newrelic-experimental/nr-showback#3] opened 2023-01-06 14:35 UTC
## The Synthetic script timeout due to large number of accounts

I'm running this with an account with 315 sub-accounts, to get a chargeback for IT department which includes about 8 accounts. Synthetic monitors and dashboards are all created successfully. However, the synthetic script failed due to timeout.

## Relevant Logs / Console output

Error: Job timed-out after 180.280837287s
    at handleScriptTimedOut (/app/synthetics-node-api-runtime/runtime/signals/signalHandlers/job-timed-out-handler.js:4:9)
    at process.<anonymous> (/app/synthetics-node-api-runtime/runtime/signals/signals.js:15:5)
    at process.emit (node:events:513:28)
    at process.emit (/app/synthetics-node-api-runtime/.pnp.cjs:13281:25)
    at Timeout.handleTimeout [as _onTimeout] (/app/synthetics-node-api-runtime/runtime/sandbox/driver.js:5:11)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)

**Comment by crshanks** [comment] 2023-02-27 14:56
@Lucy0 the timeout is caused by an issue with the public GraphQL API, which I will raise with the team responsible.  When the script is used against an organization with almost 1000 groups the service behind the public API  times out, even though pagination is requested.

I have found a workaround for the timeout by querying groups and their users, as opposed to users and their groups. This should allow the script to run on a public synthetics minion in less than 3 minutes, even for an account with > 1200 users, ~1000 groups and 300+ accounts. The fix will be released as v1.0.3 shortly.

**Closed** 2023-02-27 15:01 UTC
Labels: bug
